config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Solo necesitas resources :posts para generar todas las rutas RESTful
  resources :posts do
    resources :comments, only: [:create]
    resources :reactions, only: [:create]
  end

  # Ruta para el estado de salud de la aplicación
  get "up" => "rails/health#show", as: :rails_health_check

  # Renderizar archivos dinámicos de PWA
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Define la ruta raíz
  root "posts#index"
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string
#  body       :text
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :reactions, dependent: :destroy



  scope :post_selec, -> (post_id) { where(id: post_id) }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all.includes(:user)
  end


     
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace("post-details", partial: "posts/post_details", locals: { post: @post }) }
      format.html 
    end
  end
   

  def new
    @post = Post.new
  end


  def create
    @post = current_user.posts.new(post_params)
      if @post.save
        redirect_to @post, notice: 'Post creado exitosamente.'
      else
        render :new
      end




  end



  private

    def post_params
      params.require(:post).permit(:title, :body)
    end
  end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_details.html.erb
<div>
       <h5><%= @post.title %></h5>
          <p><%= @post.body %></p>
        <p>
          Publicado por: 
          <% if @post.user.present? %>
            <%= @post.user.name || @post.user.email %>
          <% else %>
            Usuario anónimo
          <% end %>
        </p>
fdgdfg

          <h2>Comentarios</h2>
          <%= render @comments %>
          <%= @post.user&.name %>
          <%= form_with(model: [@post, @comment]) do |f| %>
            <%= f.text_area :body %>
            <%= f.submit "Comentar" %>
          <% end %>

          <h2>Reacciones</h2>
          <%= button_to "Me gusta", [@post, Reaction.new(like: true)], method: :post %>
          <%= button_to "No me gusta", [@post, Reaction.new(like: false)], method: :post %>
</div>

app/views/posts/_form.html.erb
<!-- app/views/posts/_form.html.erb -->
<%
=begin%>
 <%= form_with(model: Post.new, local: false) do |f| %>
  <div>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content, "Content" %>
    <%= f.text_area :content %>
  </div>

  <div>
    <%= f.submit "Create Post" %>
  </div>
<% end %> 
<%
=end%>


 <!--  <h5>Comentarios</h5> -->
  <%= render @comments %>
  <%= form_with(model: [@post, @comment]) do |f| %>
      <%= f.text_area :body %>
      <%= f.submit "Comentar" %>
  <% end %>

app/views/posts/_post_details.html.erb
<!-- app/views/posts/_post_details.html.erb -->
<%= turbo_frame_tag "post-details" do %>
  <h5>
    <%= @post.title %>
  </h5>
  <p>
    <%= @post.body %>
  </p>
  <p>
    Publicado por: 
   
    <% if @post.user.present? %>
        <%= @post.user.name || @post.user.email %>
    <% else %>
          Usuario anónimo
    <% end %>
  </p>


    
  
  <div class="d-flex mb-4 ">
    <div p-2>
      <h5>Reacciones</h5>
    </div>
    <div class="p-2">
      <%= button_to post_reactions_path(@post), method: :post, params: { reaction: { like: true } }, class: "color_finger" do %>
      <%= safe_join([content_tag(:i, "", class: "fa-solid fa-thumbs-up fa-xl"), ""]) %>
      <% end %>
    </div>
    <div class="p-2">
      <%= button_to post_reactions_path(@post), method: :post, params: { reaction: { like: false } }, class: "color_finger" do %>
      <%= safe_join([content_tag(:i, "", class: "fa-solid fa-thumbs-down fa-xl"), ""]) %>
      <% end %>
    </div>
    <div class="p-2">
      <p> Reaccion agregada</p>
    </div>
  </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
<h3 class=" text-center">Publicaciones</h3>
<div class="messaging ">
      <div class="inbox_msg shadow">
        <div class="inbox_people">
          <div class="headind_srch">
            <div class="recent_heading ">
              <h4>Recientes</h4>
            </div>
            <div class="srch_bar ">
              <%
=begin%>
 <div class="stylish-input-group">
                <input type="text" class="search-bar"  placeholder="Buscar" >
                <span class="input-group-addon">
                  <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                </span> 
              </div> 
<%
=end%>
            </div>
          </div>
          <div class="inbox_chat">
            <div class="chat_list active_chat">
              <% @posts.each do |post| %>
                <div class="chat_people">
                  <div class="chat_img"> 
                    <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> 
                  </div>  
                  <div class="chat_ib">
                    <h5>
                      <!-- Link que carga dinámicamente el post en el turbo-frame -->
                      <%= link_to post.title, post_path(post), data: { turbo_frame: "post-details" } %>
                      <span class="chat_date">
                        <% last_comment = post.comments.last %>
                        <% if last_comment.present? %>
                            <p> 
                              <%= last_comment.created_at.strftime("%d %b") %>
                            </p>
                        <% else %>
                              <p>No hay comentarios aún.</p>
                        <% end %>
                      </span>
                    </h5>
                    <p>
                      <%= post.body %>
                    </p>
                    <span class="badge text-bg-secondary">
                      <i class="fa-solid fa-thumbs-up"></i><%= post.reactions.likes.count %>
                    </span> - 
                    <span class="badge text-bg-secondary">
                      <i class="fa-solid fa-thumbs-down"></i><%= post.reactions.dislikes.count %>
                    </span>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="mesgs">
          <div class="msg_history">
            <div class="incoming_msg">
              <div class="incoming_msg_img"> 
                <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> 
              </div>
              <div class="received_msg">
                <div class="received_withd_msg">
                  <div class="col-md-12 decoracion">
                    <!-- Link que carga dinámicamente los detalles de la publicación en el turbo-frame -->
                    <%= turbo_frame_tag "post-details" do %>
                        <h5>Selecciona una publicación para ver los detalles.</h5>   
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="type_msg my-2">
            <div class="input_msg_write">

           
              <%
=begin%>
 <input type="text" class="write_msg" placeholder="Type a message" />
              
              <button class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o"aria-hidden="true"></i></button> 
<%
=end%>
            </div>
          </div>
        </div>
      </div>
    
      
      <p class="text-center top_spac"> Developed by <a target="_blank" href="https://github.com/mauricio-chirino">Mauricio Chirino</a></p>
      
    </div>
  </div>

app/views/posts/new.html.erb
<h1>Crear un nuevo Post</h1>

<%= form_with model: @post, local: true do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> impidieron que el post se guardara:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "Título" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content, "Contenido" %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit "Crear Post" %>
  </div>
<% end %>

<%= link_to 'Volver', posts_path %>

app/views/posts/show.html.erb
  
<%= turbo_frame_tag "post-details" do %>
  <h5>
    <%= @post.title %>
  </h5>
  <p>
    <%= @post.body %>
  </p>
  <p>
    Publicado por: 
   
    <% if @post.user.present? %>
        <%= @post.user.name || @post.user.email %>
    <% else %>
          Usuario anónimo
    <% end %>
  </p>

  <!--  <h5>Comentarios</h5> -->
  <%= render @comments %>
  <div class="my-4">
    <%= form_with(model: [@post, @comment]) do |f| %>
        <%= f.text_area :body %>

      <%= f.submit "Comentar" %>

    <% end %>
  </div>
    
  
  <div class="d-flex mb-3 ">
    <div p-2>
      <h5>Reacciones</h5>
    </div>
    <div class="p-2">
      <%= button_to post_reactions_path(@post), method: :post, params: { reaction: { like: true } }, class: "color_finger" do %>
      <%= safe_join([content_tag(:i, "", class: "fa-solid fa-thumbs-up fa-xl"), ""]) %>
      <% end %>
    </div>
    <div class="p-2">
      <%= button_to post_reactions_path(@post), method: :post, params: { reaction: { like: false } }, class: "color_finger" do %>
      <%= safe_join([content_tag(:i, "", class: "fa-solid fa-thumbs-down fa-xl"), ""]) %>
      <% end %>
      </div>
  </div>
<% end %>